name: Mark cut

on:
  schedule:
    - cron: '5 0 * * *'

jobs:
  make-http-request:
    runs-on: ubuntu-latest
    steps:
      - name: http_request_to_mark_cut
        run: |
          curl -X POST 'https://auto-barber-schedule.vercel.app/api/go'